### ISSUE TITLE
UpdateById returns old `_rev`

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-connector-couchdb2#11]
### Reproduce

- Create a test app with a model attached to cloudant/couchdb database
- automigrate the datasource, launch the app, open the explorer
- create an instance 
- `PATCH/Notes/{id}/`: 
    - `id`: `"22f3381354bb16f90af780de8c0011b7"`
    - `data`: 
       ```js
        {
          "title": "foo",
          "content": "string",
          "_rev": "3-7b7e35cdd415c1675a220361f01900aa"
        }
       ```

- The returned data would be:
    ```
    {
      "title": "foo",
      "content": "string",
      "id": "22f3381354bb16f90af780de8c0011b7",
      "_rev": "3-7b7e35cdd415c1675a220361f01900aa" // while here it should be a new `_rev`
    }
    ```

## Acceptance Criteria
- Add unit test(s) on the `generateContextData` function to ensure that any arbitrary properties passed inwards are updated (if there is an updated value to apply) on the return pass.

**Comment by ssh24** [comment]
Can confirm this is not a bug. The above scenario returns an older `_rev` when the user does not specify the `_rev` as a model property. With the `_rev` feature, it expects the user to handle the `_rev` value requiring that property in the model definition.

**model-definition.json**
```json
{
  "name": "Employee",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true,
    "forceId": false,
    "updateOnLoad": true
  },
  "properties": {
    "_rev": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "age": {
      "type": "number"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**crud call** 
`PATCH/Notes/{id}/`:
  - id: 65901928328bde37667cddfcc8013f24
  - data: 
```json
  {
    "_rev": "2-1ae8e7ea4f8e8ca899bd10d7dfab6606",
    "name": "Foo",
    "age": 12
  }
```

**explorer output**
```json
{
  "_rev": "3-4c24e0a5dc79c5d7946762693bf8c93e",
  "name": "Foo",
  "age": 12,
  "id": "65901928328bde37667cddfcc8013f24"
}
```
