### ISSUE TITLE
findById return error when result is null

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-connector-couchdb2#14]
loopback-connector-cloudant_url/L#463 doesn't actually return `[]`

**Comment by ssh24** [comment]
@jannyHou I am not sure what the actual issue is here?

**Comment by jannyHou** [comment]
`Couchdb.prototype.find(alias findById)` is not called by any dao.js functions yet.

Plan to support optimized `findById`:
- In dao.js `DataAccessObject.findById`,
  ```
    if (connector has findById function) {
    connector.findById(id, cb)
    } else {
      this.findOne(query)
    }
  ```

**Comment by jannyHou** [comment]
@ssh24 i think it's caused by https://github.com/strongloop/loopback/blob/master/lib/persisted-model.js#L761, so it's actually an expected behavior, I mean before we implement the optimized juggler's `findById`.

**Comment by jannyHou** [comment]
I am closing this story and let's track the juggler's feature in issue https://github.com/strongloop/loopback-connector-cloudant/issues/166
