### ISSUE TITLE
cpu load goes high on the server that hosts couchdb database

### ISSUE THREAD

**Issue by ahallez** [strongloop/loopback-connector-couchdb2#39]
I just switched over from the old couchdb connector to this one, for the better support of indexes.
It seems by default couchdb puts a limit of 25 on queries and you have to put a higher limit for each request.
Is there a way removing this limit globally?

**Comment by jannyHou** [comment]
Hi @ahallez, I am glad to hear that you are interested in the indexes support :) I am afraid you can only specify `limit` in each query but cannot set up it globally. See couchdb's official document:
http://docs.couchdb.org/en/2.0.0/api/database/find.html

**Comment by ahallez** [comment]
Hi @jannyHou ,
Thanks for the reply.
I have now reverted to the connector I used before (loopback-connector-couch), still running on coucbdb 2.1, which does not have this limitation (i.e. by default the result of a query includes all matching documents).

I ran a test with the couchdb2 connector where I set the default limit in the connector code to 999, which actually worked.
However, I then noticed that the cpu load of the erl process went crazy (not sure if it has to do with the limit though, or if it is a general problem).

**Comment by jannyHou** [comment]
@ahallez IIRC, `loopback-connector-couch` leverages the view query in couchdb to specify which documents belong to a certain model(database side), and execute the request query like `where`, `order` in connector(connector side). e.g. `Test.find({where: {name: 'foo'}})` the connector finds all test instances by view query, then execute `{where: {name: 'foo'}}` on connector side.

While `loopback-connector-couchdb2` leverages `_find` query(which has the default limit of 25) in couchdb, that's probably why you only see this limit in our connector.

> I then noticed that the cpu load of the erl process went crazy

Do you mean the vm that couchdb database runs on? Interesting...I don't have a benchmark to compare the performance of view query and _find query, will try something when I have time. And the other reason I can think of is the index doesn't include all properties in a query. Could you post the full query you run with limit 999?

**Comment by ahallez** [comment]
@jannyHou There is not one particular query. My app runs dozens of different queries to load and update all the data that is needed in the webpages.
Most of the indexes are defined on a single attribute in the loopback models. Most of the queries filter on single attribute values (e.g. the parent object), however quite a lot of queries combine indexed as well as not-indexed attribute filters.

When it comes to cpu load, I noticed quite some differences between using the connectors.
With the couchdb2 connector the cpu load goes high (between 65 and 70% for the couch processes alone, 100% overall). Although the initial response times are fine, the cpu load remains high for quite a while after the page load is finished (about 10 seconds) and then goes down to single digit numbers. When multiple clients are active simultaneously, the cpu stays high, queries start to take longer and eventually start to time out.

When using the couch connector, the couchdb cpu load goes up as well, but with lower peak values (up to 50%) and after the queries are finished, the load goes down almost immediately. The accumulation of cpu load with multiple clients is far less.

**Comment by jannyHou** [comment]
@ahallez There is an index design problem I am making time to fix, suppose you use property `loopback__model__name` to specify a model name, and you have an indexable property `age`, you need to create a index in `model.json` that contains those two properties to improve the performance. I am going to create a PR to fix it soon(sorry currently busy with a release of LoopBack4).

If this is not the root reason, I will set up a benchmark to compare the view query and `_find` query. Then see how I can improve it. Appreciate your feedback. 

BTW, can you share the size of your data set? 1k documents or 1m documents, etc...

**Comment by ahallez** [comment]
@jannyHou Thanks for the follow up.
Datasets are actually quite limited for the moment. The db I was using with the couchdb2 connector had only 1.5K documents.

**Comment by jannyHou** [comment]
still active not stale

**Comment by jannyHou** [comment]
I have seen people complaining about the default limit query again. Let's use this issue to track adding a global limit config, the performance discussion afterwards is a little off topic, I am going to do the benchmark in a new issue.

Acceptance criteria:

- add a global limit config so all the queries can use it as default
- make sure user can override the global config by specifying the limit in a query

**Comment by virkt25** [comment]
Global config limit should be set through the `datasource` config + override for each method that supports this limit.

**Comment by dhmlau** [comment]
cc @rranjann

**Comment by dhmlau** [comment]
limit in `count` will be addressed in https://github.com/strongloop/loopback-connector-couchdb2/issues/41.  Moving this to backlog.

**Comment by wqj2101** [comment]
Given the comment above, are we only addressing count and find is going into the backlog? #41 only seems to reference count.

**Comment by dhmlau** [comment]
@wqj2101, we've addressed in `count` and `destroyAll`, we have [this ticket](https://github.com/strongloop-internal/scrum-apex/issues/351) to track the rest which is currently in backlog. 

cc @jannyHou

**Comment by wqj2101** [comment]
Thanks. That's good to know so we can plan accordingly. I'm getting a 404 on the ticket link, though?

**Comment by dhmlau** [comment]
It was a ticket in our internal repo.  Moving it to the right repo: https://github.com/strongloop/loopback-connector-couchdb2/issues/45.

**Comment by jannyHou** [comment]
@dhmlau I changed the title of this story to "cpu load goes high on the server that hosts couchdb database", and let's focus on the `count` implementation in https://github.com/strongloop/loopback-connector-couchdb2/issues/45

**Comment by jonathanwoahn** [comment]
Any updates on this?
