### ISSUE TITLE
Improve composed index

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-connector-couchdb2#40]
There is an index design problem I am making time to fix, suppose you use property loopback__model__name to specify a model name, and you have an indexable property age, you need to create a index in model.json that contains those two properties to improve the performance. 

## Acceptance Criteria
- [ ] Add the modelName to our indexing Design Document so queries filter for indexable properties in that model.
  - [ ] Enable it for both ways of indexing properties (Both examples shown below).
- [ ] write a blog post for the index improvement.

```js
{
  properties: {
    foo: {index: true}
  }, // the first way
  indexes: {
     composed: [foo, bar, baz]
  }  // the second way
}
```

**Comment by dhmlau** [comment]
Closing as PR#47 has landed.
