### ISSUE TITLE
Implement issues/39 for method `count`.

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-connector-couchdb2#41]
Implement https://github.com/strongloop/loopback-connector-couchdb2/issues/39 for method `count`.

**Comment by dhmlau** [comment]
cc @rranjann

**Comment by jannyHou** [comment]
waiting for https://github.com/strongloop/loopback-connector-cloudant/pull/183

**Comment by jannyHou** [comment]
The fix should be in loopback-connector-cloudant@1.x as well

**Comment by wqj2101** [comment]
I see code that's been merged for the cloudant connector. Is the port to couchdb2 connector going to happen as well?

**Comment by dhmlau** [comment]
according to this merged PR https://github.com/strongloop/loopback-connector-couchdb2/pull/42, it is.

**Comment by wqj2101** [comment]
The merge is saw in that PR was for cloudant. I did not see a merge for couch which is why I asked.

**Comment by dhmlau** [comment]
It's merged and released in `1.2.0`.  Is it something you're looking for?

**Comment by wqj2101** [comment]
Yes, we're looking to use it as soon as it's ready. We'll test it out,
thanks!

**Comment by jannyHou** [comment]
@dhmlau The PRs related to this issue are all merged, but in terms of solving the interrupt, the internal people says it doesn't work with their Cloudant local. I pinged the corresponding internal people to give me their steps of installing the database, will continue the investigation then.

**Comment by jannyHou** [comment]
I am closing this issue since PR merged. If you find any specific version of Couchdb/Cloudant doesn't work with it, feel free to reopen it we will continue investigation!
