### ISSUE TITLE
No support for Date Array types

### ISSUE THREAD

**Issue by cwilko** [strongloop/loopback-connector-couchdb2#43]
In Couchdb.js, the CouchDB.prototype.selectModel function has the following code to identify Date properties in the model. Further downstream the dateFields array is used to convert these properties to Date objects. However, if the property in the model is an Array type (e.g. an array of Dates) then this won't work ( mo.properties[p].type.name will be "undefined" )
 
```
for (var p in mo.properties) {
    if (mo.properties[p].type.name === 'Date') {
      dateFields.push(p);
  }
}
```

**Comment by cwilko** [comment]
Pull request #44 created

**Comment by jannyHou** [comment]
@cwilko appreciate your contribution! https://github.com/strongloop/loopback-connector-couchdb2/pull/44 looks cool to me, please add some test for it and I will help you land the PR, thanks.
