### ISSUE TITLE
Set Query Limit Globally/Via Datasource Configuration

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-connector-couchdb2#45]
connected to https://github.com/strongloop/loopback-connector-couchdb2/issues/39

## Overview

I have seen people complaining about the default limit query again. Let's use this issue to track adding a global limit config, the performance discussion afterwards is a little off topic, I am going to do the benchmark in a new issue.

## Acceptance Criteria

- [ ] add a global limit config so all the queries can use it as default
  - [ ]  "all the queries" means at least find and count
      - [x] `count`
      - [x] `destroyAll`
  - [ ]    apply to any other methods? to be investigated
- [ ]     make sure user can override the global config (set in datasource) by specifying the limit in a query (and any other methods that support this limit).
- [ ]     Verify Cloudant connector works with this as well (should all just be inherited).
- [ ]     Verify DB returns Error for invalid limits (0, negative numbers, Infinity, etc.)

_This is originated from https://github.com/strongloop-internal/scrum-apex/issues/351.  Moving it to this repo_

**Comment by dhmlau** [comment]
currently only implemented in count and destroyAll

**Comment by dhmlau** [comment]
@wqj2101.  I believe this is the one you're looking for.

**Comment by jannyHou** [comment]
nope

**Comment by wqj2101** [comment]
This is still an issue. Thanks! The count portion definitely works (which is great!).
