### ISSUE TITLE
At connector level, `all` should call `findById` under the hood for a lookup

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-connector-couchdb2#46]
# Description/Steps to reproduce

 **We allow `findById` at the datasource level. But we want to have it at model level.**

Currently user has to call connector level method `server.datasources.cloudantDB.connector.findById` to get an instance by lookup query, it doesn't return a LB model instance but a plain JSON object. 
Considering the huge effort to enable `findById` at juggler level, see discussion in [PR](https://github.com/strongloop/loopback-datasource-juggler/pull/1459#issuecomment-357534776), I would suggest adjust the code at connector level.

# Acceptance criteria

- [ ] Pass an option flag from juggler function `find()` to connector function `all()` to indicate the initial call is from juggler's `findById()`. 
- [ ] In the connector function `all()`, calls drive's lookup api instead of query api when the flag is `true`.

# Expected result

Assume a LB model `Order` is attached to cloudant datasource, when call the LB model method `findById`, it calls driver's lookup function under the hood, not query.

```js
Order.findById('order1', done)
```

**Comment by dhmlau** [comment]
@jannyHou , please correct me if I'm wrong... I think the rationale behind this issue is currently the Cloudant service on IBM Cloud has different limit and pricing on lookup vs query.  We allow `findById` at the datasource level, but we also want `findById` at the connector level, that's why we have this issue opened.

**Comment by jannyHou** [comment]
> We allow findById at the datasource level, but we also want findById at the connector level, that's why we have this issue opened.

Almost correct, we allow `findById` at the datasource level and we want to have it at **model** level. 
Your highlight description is better than mine, I updated the story.

**Comment by dhmlau** [comment]
Based on @jannyHou 's description, moving it to `needs discussion` column.

**Comment by dhmlau** [comment]
@jannyHou , could you please add the pros/cons for your proposals to initiate the discussion? thanks.

**Comment by jannyHou** [comment]
@dhmlau I think the second proposal is just a bad idea. Let's discuss based on first proposal :)
