### ISSUE TITLE
Regex issues with "like and nlike"

### ISSUE THREAD

**Issue by Danwakeem** [strongloop/loopback-connector-couchdb2#51]
# Description/Steps to reproduce
If you try and run a `like` or `nlike` query using javascript regular expression syntax you get a blank `$regex` operator.

```
name: 'Error',
  error: 'invalid_operator',
  reason: 'Invalid operator: $regex',
  scope: 'couch',
  statusCode: 400,
.....
body: '{"selector":{"loopback__model__name":"Post","$and":[{"loopback__model__name":"Post","keyword":{"$regex":{}}}]},....
```

# Link to reproduction sandbox

[Loopback-Sandbox repo](https://github.com/Danwakeem/loopback-sandbox)
* You should be able to pull this project down, install dependancies, run `source setup.sh`, and start the server to see the issue (It's all in the `README`).
> Specifically [these are the lines](https://github.com/Danwakeem/loopback-sandbox/blob/master/common/models/my-model.js#L28-L34) where we can see how the javascript regex does not work where the PCRE regex does work.

# Expected result

```
{
  "data": [
    {
      "keyword": "abc",
      "id": "sample_doc",
      "_rev": "1-efe66b28ebdb02928354bd357074d562"
    }
  ]
}
```
### Actual Result
```
{
  "error": {
    "statusCode": 400,
    "name": "Error",
    "message": "Invalid operator: $regex"
  }
}
```

# Additional information
This error was opened as an issue here strongloop/loopback-connector-cloudant#189 but appears to originate from this project.

It seems that both CouchDB and Cloudant require [PCRE style regular expressions](http://docs.couchdb.org/en/2.1.1/api/database/find.html) but the [loopback documentation ](https://loopback.io/doc/en/lb2/Where-filter.html#like-and-nlike-insensitive) implies that you can use the javascript `RegExp`.

**Comment by jannyHou** [comment]
fixed in https://github.com/strongloop/loopback-connector-couchdb2/pull/52, thanks!

Feel free to reopen it if you have other questions.
