### ISSUE TITLE
Have CIs run consistently across all PRs

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-connector-couchdb2#53]
Currently, there's no CIs that run the tests for this repo.

EDIT: from @virkt25 https://github.com/strongloop/loopback-connector-couchdb2/issues/53#issuecomment-403131740:
> There seem to be some tests but for some PRs it looks like the CI just doesn't run ... 

> Click `See Detail` for this PR and there are 10 checks that ran.
> https://github.com/strongloop/loopback-connector-couchdb2/pull/54

# Description/Steps to reproduce

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by virkt25** [comment]
There seem to be some tests but for some PRs it looks like the CI just doesn't run ... 

Click `See Detail` for this PR and there are 10 checks that ran.
https://github.com/strongloop/loopback-connector-couchdb2/pull/54
