### ISSUE TITLE
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value: assert(doc._id)

### ISSUE THREAD

**Issue by DannyFournier** [strongloop/loopback-connector-couchdb2#62]
# Description/Steps to reproduce

I am attempting to load documents into CouchDB using Loopback's API Explorer. The loading is done using a shell script that uses the cURL command to PUT local files through to the API.

The first document will get added to the database. It will be visible in Fauxton. However, the NodeJS server crashes with the following error:

> assert.js:350
>     throw err;
>     ^
> 
> AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
> 
>   assert(doc._id)
> 
>at CouchDB.fromDB (/home/dan/projects/myapp/node_modules/loopback-connector-couchdb2/lib/couchdb.js:163:3)
>     at /home/dan/projects/myapp/node_modules/loopback-connector-couchdb2/lib/couchdb.js:701:21
>     at Request._callback (/home/dan/projects/myapp/node_modules/nano/lib/nano.js:221:16)
>     at Request.self.callback (/home/dan/projects/myapp/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:189:13)
>     at Request.<anonymous> (/home/dan/projects/myapp/node_modules/request/request.js:1161:10)
>     at Request.emit (events.js:189:13)
>     at IncomingMessage.<anonymous> (/home/dan/projects/myapp/node_modules/request/request.js:1083:12)
>     at Object.onceWrapper (events.js:277:13)
>     at IncomingMessage.emit (events.js:194:15)
>     at endReadableNT (_stream_readable.js:1125:12)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! my-app@1.0.0 start: `node .`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the my-app@1.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:

Steps to reproduce are:

1. Clone the following repository: https://github.com/DannyFournier/myapp
2. Run `docker-compose up -d` to instantiate an instance of CouchDB. If an instance is already up, simply modify the url attribute accordingly in `src/datasource/couchdb.datasource.json`
3. Run `npm install`
4. Run `npm start`
5. In another prompt, run the script located at: `script/init_db_custom_id_nodejs.sh`

# Additional information

I am not able to reproduce the error by using the API Explorer in my browser. I can copy paste the content of the local files and manually specify the Id without triggering the error.

Output of node command:

> linux x64 10.15.3

Output of npm command:

> ├── @loopback/boot@1.2.3
> ├── @loopback/context@1.12.0
> ├── @loopback/core@1.6.0
> ├── @loopback/openapi-v3@1.3.7
> ├── @loopback/repository@1.5.1
> ├── @loopback/rest@1.10.4
> ├── @loopback/rest-explorer@1.1.18
> ├── @loopback/service-proxy@1.1.6
> └── loopback-connector-couchdb2@1.3.0

**Comment by AndersonEngenheiro** [comment]
I solve this issue with this instructions: https://segmentfault.com/a/1190000041958374/en###
But in my case, I use the path below to put the file:

C:\Users\assouza \ .cache\v3.4
