### ISSUE TITLE
Loopback PUT operation not working as expected

### ISSUE THREAD

**Issue by manojsaxenatda** [strongloop/loopback-connector-couchdb2#64]
Hi,
 
We are currently using Loopback for a couchDb database using loopback-connector-couchdb2. We discovered that using a Loopback PUT operation to modify an existing resource was not working as expected.  We looked into what loopback-connector-couchdb2 is doing, and it looks like the Loopback PUT is being translated into a nano POST operation, instead of PUT. We’ve confirmed that doing a direct couchDb HTTP API call using PUT does work.
 
Looking further, in nano, insertDoc(nano.js: line 416) invokes Http PUT method towards couchDb only if second parameter 'qs' is defined.  In the current version of loopback-connector-couchdb2, couchdb.js (line: 198) is invoked with only two arguments: 'doc' and 'callback function'.  We think the additional parameter is needed in this line of code, and this is the reason why modify existing resource on couchDB is failing.
 
Would it be possible to get this bug fixed?
 
Thank you for your help and support.

-------
`187 /** 

188  * Insert a model instance 
189  * 
190  * @param {String} model The model name 
191  * @param {Object} data The model data 
192  * @callback {Function} cb The callback function 
193  */ 
194 CouchDB.prototype._insert = function(model, data, cb) { 
195   var self = this; 
196   var idName = self.idName(model); 
197   var mo = self.selectModel(model); 
198   mo.db.insert(self.toDB(model, mo, data), function(err, result) { 
`

**Comment by jannyHou** [comment]
Hey @manojsaxenatda the `PUT` operation in this connector does a local data merge then invoke the `POST` from nano. 

IIRC couchdb only supports a entire replace but not a patch, that why the update method was designed as that.

> Looking further, in nano, insertDoc(nano.js: line 416) invokes Http PUT method towards couchDb only if second parameter 'qs' is defined. In the current version of loopback-connector-couchdb2, couchdb.js (line: 198) is invoked with only two arguments: 'doc' and 'callback function'. We think the additional parameter is needed in this line of code, and this is the reason why modify existing resource on couchDB is failing.

Thanks for the investigation, the proposal looks reasonable to me. Would you be interested to submit a PR to fix the update methods? I will help you review and land it :)

**Comment by manojsaxenatda** [comment]
Hi Janny,

Thank you for the quick response.

I would be happy to submit a PR for your review.

-Manoj
